#!/usr/bin/env fish
#MISE description="Install Fisher (Fish shell plugin manager)"
#MISE depends=["check-exists fish"]

set fisher_repo "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"

if ! functions -q fisher
    curl -sL $fisher_repo | source && fisher install
end

fisher update
